### ISSUE TITLE
Error in plugin-theming

### ISSUE THREAD

**Issue by stXwinter** [RCVolus/league-prod-toolkit#142]
Main PC:
![image](https://user-images.githubusercontent.com/44768100/194996861-7931b05e-ddc2-42eb-aa11-3914e99df832.png)

Second PC:
![unknown](https://user-images.githubusercontent.com/44768100/195000704-b2db9a24-eaba-4ac9-9a0f-e018404c9cf5.png)

**Comment by sdomi4** [comment]
The issue on the main PC should be fixed by rerunning the `npm install` command in the toolkit directory (Shift+rightclick in the folder -> Open PowerShell window here -> run `npm install`.
The warning on the second PC should disappear once you select a different theme on the configuration page.

**Comment by stXwinter** [comment]
I ran the npm install on the directory and i'm still encountering the same issue.

![123](https://user-images.githubusercontent.com/44768100/195555653-a9aef4e4-3c65-456a-82d1-df3e83aae27f.PNG)
![1234](https://user-images.githubusercontent.com/44768100/195555663-1e353b4e-1a04-467e-9e04-95d545b2fe89.PNG)

**Comment by Himyu** [comment]
issues in the plugin theming should be fixed now with version v1.2.6.
